### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by graveship** [DNYLA/Labmaker#12]
Create a landing page for the Dashboard which showcases main features and possibly includes an FAQ/Roadmap.

### Why?
Adding a landing page would be more sensible this then allows new users to see the features we provide before logging in via discord as they might want to look around before signing up/in.

This will most likely be done as the final addition to V2 or may even get done once V2 is released as it is not that important.

**Comment by IRHM** [comment]
@DNYLA Some of the spacing and sizing looks a little off, but this is the general idea for the design. If it looks good, I can finish off designing the other pages, but they'll end up looking pretty much the same as this.

![Home Page](https://user-images.githubusercontent.com/37304121/147847041-8126a71d-80b9-4a32-bddb-468aeb1071bf.png)

I figured it would look nicer if a modal showed up for the settings that needed something like this rather than having it inline:
![Modal](https://user-images.githubusercontent.com/37304121/147847066-b652997d-5822-46c2-946d-b10fee521907.png)

**Comment by graveship** [comment]
New UI Created

Landing Page wont be added due to this page only being accessed by admins.

A Tutor/Client Dashboard will be created.
